package ru.geekbrains.models;

public enum Commands {
    DOWNLOAD,
    LOGIN,
    REGISTER,
    FIND_USER,
    AUTHENTICATED,
    NOT_AUTHENTICATED,
    REGISTERED,
    NOT_REGISTERED,
    USER_FOUND,
    USER_NOT_FOUND,
    COPY,
    DELETE,
    GET_DIRECTORY,
    SEND_CURRENT_PATH,
    CREATE_DIRECTORY,
    UP_TO_PATH,
    BACK_TO_PATH,
    CURRENT_PATH,
    FILE_SIZE,
    FILE_LIST,
    STATUS,
    PART_FILE,
    PART_FILE_INFO,
    FILTER_FILE_LIST
}
